package dahal_ajaya_binfer;
// Generated Jan 11, 2019 3:28:53 AM by Hibernate Tools 4.3.1

import javafx.scene.control.CheckBox;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * ResultQuery generated by hbm2java
 */
public class ResultQuery  implements java.io.Serializable {

    @Id
    
//    @GeneratedValue(strategy = GenerationType.AUTO)
//    @Column(name = "id", updatable = false, nullable = false)
    private short id;
    

     private CheckBox checkbox;
     @Column
     private boolean checkBox;
     @Column
     private String title;
     @Column
     private String summary;

    public ResultQuery() {
    }

	
    public ResultQuery(short id) {
        this.id = id;
    }
    public ResultQuery(short id, CheckBox checkbox, String title, String summary) {
       this.checkbox=new CheckBox();
       this.checkBox = this.checkbox.isSelected();
       this.title = title;
       this.summary = summary;
       this.id = id;
       
       
       
    }
    public ResultQuery(short id, Boolean checkBox, String title, String summary) {
       this.checkbox=new CheckBox();
       this.checkBox = checkBox;
       this.title = title;
       this.summary = summary;
       this.id = id;
    }
    
    public ResultQuery( short id, String title, String summary) {
       this.checkbox=new CheckBox();
       this.checkBox = checkbox.isSelected();
       this.title = title;
       this.summary = summary;
       this.id = id;
    }
    
//    public ResultQuery(short id, CheckBox checkbox, String title, String summary) {
//       this.id = id;
//       this.checkBox = new CheckBox();
//       this.title = title;
//       this.summary = summary;
    
    public ResultQuery(  String title, String summary) {
       this.checkbox=new CheckBox();
       this.checkBox = checkbox.isSelected();
       this.title = title;
       this.summary = summary;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public CheckBox getCheckbox() {
        return this.checkbox;
    }
    
    public void setCheckbox(Boolean checkBox) {
        this.checkbox.setSelected(this.checkBox);
        this.checkBox = checkBox;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * @param checkbox the checkbox to set
     */
   

    /**
     * @return the checkBox
     */
    public boolean getCheckBox() {
        return checkBox;
    }

    /**
     * @param checkBox the checkBox to set
     */
    public void setCheckBox(boolean checkBox) {
        this.checkBox = checkBox;
    }




}


